/// ==========================================================================
/// correlation.dart — Correlation / Insight Entity
/// ==========================================================================
/// Represents a detected correlation between a symptom and a lifestyle
/// factor (trigger). Generated by the insight engine after analyzing
/// 30+ days of logs.
///
/// Fields:
/// - symptom: the symptom involved
/// - trigger: the lifestyle factor correlated
/// - frequency: how often this correlation was observed
/// - severityCorrelation: strength of the correlation (0.0 – 1.0)
/// - predictedRisk: predicted risk for the next occurrence (premium)
/// - summary: plain-language explanation (AI-generated)
/// - detectedAt: when the correlation was first detected
/// ==========================================================================

import 'dart:convert';
import 'symptom_log.dart';

class Correlation {
  final String id;
  final String userId;
  final SymptomType symptom;
  final String trigger; // e.g., "low sleep", "high stress", "poor diet"
  final int frequency; // number of co-occurrences
  final double severityCorrelation; // 0.0 (no correlation) – 1.0 (strong)
  final double? predictedRisk; // 0.0 – 1.0, premium feature
  final String? summary; // AI-generated plain-language insight
  final DateTime detectedAt;
  final DateTime updatedAt;

  const Correlation({
    required this.id,
    required this.userId,
    required this.symptom,
    required this.trigger,
    required this.frequency,
    required this.severityCorrelation,
    this.predictedRisk,
    this.summary,
    required this.detectedAt,
    required this.updatedAt,
  });

  // ── Firestore Serialization ──

  factory Correlation.fromMap(Map<String, dynamic> map) {
    return Correlation(
      id: map['id'] as String,
      userId: map['userId'] as String,
      symptom: SymptomType.values.firstWhere(
        (e) => e.name == map['symptom'],
        orElse: () => SymptomType.other,
      ),
      trigger: map['trigger'] as String,
      frequency: map['frequency'] as int,
      severityCorrelation: (map['severityCorrelation'] as num).toDouble(),
      predictedRisk: (map['predictedRisk'] as num?)?.toDouble(),
      summary: map['summary'] as String?,
      detectedAt: _parseDate(map['detectedAt']),
      updatedAt: _parseDate(map['updatedAt']),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'symptom': symptom.name,
      'trigger': trigger,
      'frequency': frequency,
      'severityCorrelation': severityCorrelation,
      'predictedRisk': predictedRisk,
      'summary': summary,
      'detectedAt': detectedAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  // ── JSON Convenience ──

  factory Correlation.fromJson(String source) =>
      Correlation.fromMap(json.decode(source) as Map<String, dynamic>);

  String toJson() => json.encode(toMap());

  // ── Computed Properties ──

  /// Returns a human-readable strength label for this correlation.
  String get strengthLabel {
    if (severityCorrelation >= 0.7) return 'Strong';
    if (severityCorrelation >= 0.4) return 'Moderate';
    return 'Weak';
  }

  /// Whether this correlation is considered statistically significant.
  /// Requires at least 3 co-occurrences and moderate strength.
  bool get isSignificant => frequency >= 3 && severityCorrelation >= 0.4;

  // ── Copy ──

  Correlation copyWith({
    String? id,
    String? userId,
    SymptomType? symptom,
    String? trigger,
    int? frequency,
    double? severityCorrelation,
    double? predictedRisk,
    String? summary,
    DateTime? detectedAt,
    DateTime? updatedAt,
  }) {
    return Correlation(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      symptom: symptom ?? this.symptom,
      trigger: trigger ?? this.trigger,
      frequency: frequency ?? this.frequency,
      severityCorrelation: severityCorrelation ?? this.severityCorrelation,
      predictedRisk: predictedRisk ?? this.predictedRisk,
      summary: summary ?? this.summary,
      detectedAt: detectedAt ?? this.detectedAt,
      updatedAt: updatedAt ?? DateTime.now(),
    );
  }

  @override
  String toString() =>
      'Correlation(${symptom.name} ↔ $trigger, strength: $strengthLabel)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Correlation && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

// ── Helper ──

DateTime _parseDate(dynamic value) {
  if (value is String) return DateTime.parse(value);
  if (value != null && value is! String) {
    try {
      return (value as dynamic).toDate() as DateTime;
    } catch (_) {
      return DateTime.now();
    }
  }
  return DateTime.now();
}
